apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blogmates-cert
spec:
  secretName: blogmates-tls-secret
  issuerRef:
    name: blogmates-tls-secret
    kind: ClusterIssuer
  dnsNames:
  - blogmates-app.com 