apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: blogmates-tls-secret
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: vladstanciu18@gmail.com
    privateKeySecretRef:
      name: blogmates-tls-secret
    solvers:
    - http01:
        ingress:
          class: nginx