apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-parsers
  namespace: monitoring
data:
  parsers.conf: |
    [PARSER]
        Name        docker
        Format      regex
        Regex       ^(?<time>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d+Z) (?<stream>stdout|stderr) F (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%LZ
        Time_Keep   On

    [PARSER]
        Name        json
        Format      json
        Time_Key    asctime
        Time_Format %Y-%m-%d %H:%M:%S
        Time_Keep   On

    [PARSER]
        Name        gunicorn
        Format      regex
        Regex       ^\[(?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} \+0000)\] \[(?<pid>\d+)\] \[(?<level>[A-Z]+)\] (?<message>.*)$
        Time_Key    time
        Time_Format %Y-%m-%d %H:%M:%S %z
        Time_Keep   On 