apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: monitoring
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Daemon       Off
        Log_Level    debug
        Parsers_File /fluent-bit/etc/parsers.conf

    [INPUT]
        Name        tail
        Path        /var/log/containers/blogmates-backend*.log
        Parser      docker
        Mem_Buf_Limit  50MB
        Skip_Long_Lines On
        Tag         kube.*
        Refresh_Interval 5
        Read_from_Head On

    [FILTER]
        Name        parser
        Match       kube.*
        Key_Name    log
        Parser      json
        Reserve_Data On

    [FILTER]
        Name        kubernetes
        Match       kube.*
        Merge_Log   On
        Keep_Log    On
        K8S-Logging.Parser    Off
        K8S-Logging.Exclude   Off
        Labels      On
        Annotations On
        Use_Journal Off
        Kube_URL    https://kubernetes.default.svc:443
        Kube_CA_File /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix kube.var.log.containers.
        Merge_Log_Key log_processed

    [FILTER]
        Name        modify
        Match       kube.*
        Copy        kubernetes.namespace_name namespace
        Copy        kubernetes.container_name container
        Copy        kubernetes.pod_name pod
        Copy        kubernetes.pod_id pod_id
        Copy        kubernetes.docker_id container_id
        Copy        kubernetes.host host
        Copy        levelname level
        Copy        funcName func
        Copy        asctime timestamp
        Copy        message log_message
        Add         app blogmates-backend
        Add         environment production

    [OUTPUT]
        Name        loki
        Match       kube.*
        Host        loki.monitoring.svc.cluster.local
        Port        3100
        Labels      app=blogmates-backend
        Remove_Keys kubernetes,stream,levelname,funcName,name,asctime,app_extracted
        Label_Keys  $level,$func,$timestamp,$log_message
        Auto_Kubernetes_Labels  On
        Tenant_ID   blogmates

    [OUTPUT]
        Name        stdout
        Match       * 